### ISSUE TITLE
Wanna know about this project.

### ISSUE THREAD

**Issue by luckypal** [jjkeijser/connect-proxy#1]
Hello, I have very interested in this project and wanna know the correct and detailed description about this project.
Can you explain?
And I wanna take part here.
Thanks.

**Comment by jjkeijser** [comment]
What would you like to know?  I have no changes upcoming, nor change requests for this particular project.

**Comment by luckypal** [comment]
I wanna know the main purpose of this project.

**Comment by jjkeijser** [comment]
the purpose of this tool is to set up a connection to a server/service via a  proxy server. Some companies and especially some airport wifi setups do not allow direct connections to a server/service without passing through a proxy server first. This tool allows a user to do that on the commandline via either an HTTP, HTTPS, SOCKS or telnet proxy. This is used most often in combination with SSH, e.g. to use a plain HTTP proxy:
  ssh -o "ProxyCommand connect-proxy -H &lt;proxy-server&gt;  %h %p"   &lt;hostname &gt;

**Comment by luckypal** [comment]
I see, Thanks for your guide.
